### ISSUE TITLE
Tweak settings window

### ISSUE THREAD

**Issue by ArtificialQualia** [ArtificialQualia/PyEveLiveDPS#22]
Currently, the settings window is clunky and confusing.  Some minor readability improvements could make it more readable, but more thorough settings window overhaul should be investigated to better navigate the number of options that are now available.  Maybe via tabs or a sidebar.

**Comment by ArtificialQualia** [comment]
The minor readability enhancements have been added.  Leaving this ticket open as a reminder to do the rest of the overhaul.

Full overhaul to come at a later time, either when the settings window gets added onto again and gets even more clunky, or when I have an excessive amount of free time or am feeling sadistic enough to mess around with UX for hours.

**Comment by Khaemwese** [comment]
You might want to consider the bellow change as well...
Using Linux, the inner frame in the setting box is too narrow and it was impossible to read the total content as well as select most of the options. I'm not sure if that would have an adverse effect in Windows though.

/PyEveLiveDPS/settingsWindow.py
```
-        self.scrollableCanvas = tk.Canvas(linesFrame, borderwidth=0, height="350")
+        self.scrollableCanvas = tk.Canvas(linesFrame, borderwidth=0, height="350", width="540")
```

**Comment by ArtificialQualia** [comment]
@Khaemwese interesting that this doesn't behave the same way as it does in Windows since tkinter is supposed to behave the same across platforms.  I'll add this in for better linux compatibility.

**Comment by Khaemwese** [comment]
There is a chance it was caused by my settings as well, I tend to mess around with default Font sizes to be easier to read and didn't really look if there was a way to make the font smaller, so it would fit. I figured it would be easier to widen the window instead.
And thanks again for creating this tool!

**Comment by ArtificialQualia** [comment]
Actually yeah, it appears you are right.  Peld is currently configured to use system default fonts, and even in my testing in linux the current size should be sufficient.  I thought based on your initial comment the inner scrollable canvas wasn't taking up the whole window size, but it makes more sense that this is happening if your default font size is larger.

In that case, we don't want to just make the window larger since that will look very strange for people using regularly sized fonts.  There are a few ways to handle this, but since I want people to be able to use their selected default font, I think what I'll do is these two things:  
- handle resizing the settings window a little better.  This would allow you to expand the settings window and have things fill up the extra space so you can see everything.  
- use font measurements to make the window as wide as it needs to be to fit all the text by default.

I'll add that in with the other settings window overhaul stuff I plan to do.  I'll also work on adding it to some of the other popup windows (like the simulation window, profile window, etc.) so we don't encounter this problem there as well.
