### ISSUE TITLE
Need a couple of fixes to run on Linux.

### ISSUE THREAD

**Issue by Khaemwese** [ArtificialQualia/PyEveLiveDPS#25]
Thanks for creating this. I've always had the log window open (never really liked the on-screen damage), but with everything that goes on, I can never really see how much DPS I'm taking or applying. This will, hopefully, change that for me!

Below are a couple of changes I had to make to run in Arch Linux with Python 3.6 that I think would apply to all Linux distros:

PyEveLiveDPS/logreader.py
```
-import win32com.client
+if (platform.system() == "Windows"):
+    import win32com.client
```

PyEveLiveDPS/mainWindow.py
```
-import idlelib.ToolTip
-from ctypes import windll
 import platform
+if (platform.system() == "Windows"):
+    import idlelib.ToolTip
+    from ctypes import windll
+else:
+    import idlelib.tooltip
```

**Comment by ArtificialQualia** [comment]
@Khaemwese Thanks for the additions, I had this working on linux with the initial release, but as is pretty clear I do most of my dev work and testing on Windows as that is where I have Eve installed.

I'll add these into the main codebase, and actually idlelib.ToolTip can be removed entirely.  Tooltips weren't behaving the way I wanted to with the window.  I must have just forgotten to remove that line.

If you want credit for these changes you can make a pull request, but if you don't care I'll just throw them in.

**Comment by Khaemwese** [comment]
I don't really care... I'm still learning how to use github and besides, I intent to use you software on Linux and since you're doing most of the work on Windows, I'm sure there will be other opportunities to collaborate.

**Comment by ArtificialQualia** [comment]
Added in 	be8ec28
