### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Born2030** [ArtificialQualia/PyEveLiveDPS#44]
Good afternoon.
updated its version of PELD to 2.3.0 and it stopped running.
https://prnt.sc/kwim00
after that it closes and everything (((What could be the problem?

**Comment by ArtificialQualia** [comment]
Hi @Born2030 

Can you attach the PELD log file, found here:  
`C:\Users\[username]\AppData\Roaming\PELD\PELD.log`

That should help me diagnose this issue.

**Comment by Born2030** [comment]
[PELD.log](https://github.com/ArtificialQualia/PyEveLiveDPS/files/2401193/PELD.log)

**Comment by ArtificialQualia** [comment]
Thank you, I see the issue now.  I should have a fix for this later today.

**Comment by Born2030** [comment]
Thank you for your prompt response and for the program.

**Comment by ArtificialQualia** [comment]
This has been fixed in v2.3.1

**Comment by Born2030** [comment]
the program start but no one picks up the logs of the damage. does not show graphs

**Comment by Born2030** [comment]
http://prntscr.com/kwwwte
