### ISSUE TITLE
Graph does not scale

### ISSUE THREAD

**Issue by Sutima** [ArtificialQualia/PyEveLiveDPS#45]
Using latest version of Peld, installed it fresh, and the graph does not scale 
https://i.imgur.com/cNlGFEA.png

Tell me what other info you need :) 
Logs https://drive.google.com/open?id=1oxQQqEKs_cS2aCigdLWIIw2Zzgr4_HmH
Edit: Found the log and added log file.

**Comment by ArtificialQualia** [comment]
Thanks for providing all that info, it appears there is something unique to your settings that is causing this behavior, but I'm not sure what yet.  I'll do some more investigating and let you know what I find.

**Comment by ArtificialQualia** [comment]
It's actually not specific to your settings, it seems to be a rare case that just happens more frequently with your settings.  I've identified a fix and should have a new version out later today.

**Comment by ArtificialQualia** [comment]
This has been fixed in v2.3.1
