### ISSUE TITLE
Nope

### ISSUE THREAD

**Issue by Born2030** [ArtificialQualia/PyEveLiveDPS#47]
the program start but no one picks up the logs of the damage. does not show graphs

http://prntscr.com/kwwwte

**Comment by Born2030** [comment]
[PELD.log](https://github.com/ArtificialQualia/PyEveLiveDPS/files/2404149/PELD.log)

**Comment by ArtificialQualia** [comment]
I've tested with both NPC and regular player combat in Russian with v2.3.1 and it is working fine for me.  Were you tracking the right character?

**Comment by ArtificialQualia** [comment]
Nevermind, I see the issue now.

It appears CCP has changed the log format... but not for English logs.  I had some old Russian logs I was using for testing that in damage entries said this:  
`Ущерб [number] наносит удар по` or ` Ущерб [number] удар от` for damage out/in

but now the logs just say `на` or `из`!

I'm going to have to get all new sample logs for all the non-english languages to make sure there weren't anymore hidden changes...  I should have something out today or tomorrow.

**Comment by ArtificialQualia** [comment]
This has been fixed in v2.3.2
