### ISSUE TITLE
[Enhancement] Display max dps in/out, max RR received/given, Neutralizing amount

### ISSUE THREAD

**Issue by SubjectXXX** [ArtificialQualia/PyEveLiveDPS#49]
Sometimes Its hard to always look at the screen and check numbers and remember them.
Next to DPS Out and DPS In should also be label (or popup) with DPS Max values and these values retained through the session (Sometimes fighting gets a little break, pulling range or reloading etc).

I would add this stuff, but never used python before and its alot different than php..

**Comment by SubjectXXX** [comment]
NVM, found that in settings.. :)

**Comment by SubjectXXX** [comment]
Or not, missread the setting., OMG..

**Comment by ArtificialQualia** [comment]
I can see this being useful, I'll look at implementing this

**Comment by SubjectXXX** [comment]
Awesome.

Sorry for close - reopen mess :)

**Comment by ArtificialQualia** [comment]
This has been added in [v2.4.0](https://github.com/ArtificialQualia/PyEveLiveDPS/releases/tag/v2.4.0)
