### ISSUE TITLE
.md not able to open

### ISSUE THREAD

**Issue by NormannK** [ArtificialQualia/PyEveLiveDPS#55]
normal systems don't have a viewer for .md files
![1](https://user-images.githubusercontent.com/23198136/67145100-95878b00-f27e-11e9-837d-9bca60ef2974.png)
![2](https://user-images.githubusercontent.com/23198136/67145103-9ae4d580-f27e-11e9-84bf-722043dca69b.png)

**Comment by ArtificialQualia** [comment]
I may just remove the view readme option altogether.  You can open it in any text file editor, but it looks like garbage if the markdown isn't interpreted.  It's written for github really.

**Comment by ArtificialQualia** [comment]
this has been removed in v2.5.1
