### ISSUE TITLE
Documentation should explain need for overview settings.

### ISSUE THREAD

**Issue by cvweiss** [ArtificialQualia/PyEveLiveDPS#67]
Using log parsers in the past, I've never had to provide information on overview settings. This is confusing for a user new to PELD, and the need is not explained. Perhaps the README could contain some information?

**Comment by ArtificialQualia** [comment]
Good point, ideally that should be known going into using PELD for the first time and not a surprise when you first start it.  I've added a section to the README for that.

Thanks for the suggestion.
