### ISSUE TITLE
Can I use your regular expressions for my log analyzer?

### ISSUE THREAD

**Issue by Lazersquid** [ArtificialQualia/PyEveLiveDPS#69]
Hey,
I created my own small log analyzer and want to open source it sometime in the future, but it can only read english logs currently.
Can I use your regular expressions to support other languages as well?

**Comment by ArtificialQualia** [comment]
This code is licensed under the [GPL v3.0](https://www.gnu.org/licenses/quick-guide-gplv3.html).  This means generally you can use my code in your project.  However (to the best of my understanding of the license, read the link for more details, I am not a lawyer, etc.) to anyone who is provided your final application, they must also be able to access the source code for the application.  This is what is called a 'copy-left' license.

If you are using this code in your own personal project, no problem!  You're free to do whatever with it.

If you are using this code in an application you are distributing to others, and it is open source (e.g. on github or similar), then no problem!  Use it to your heart's content.

If you, for instance, are using this code in a closed-source project that you will sell to others and not provide the source code for, then that would be in violation of the license.

Feel free to reopen this ticket if you have further questions.  Good luck!

**Comment by Lazersquid** [comment]
I see, thank you!
