### ISSUE TITLE
PELD doesnt work for me with the new eve patch

### ISSUE THREAD

**Issue by Zoups67** [ArtificialQualia/PyEveLiveDPS#71]
Hello ! 
I was using PELD successfully the other day, but since the last eve patch it seems the application cant read eve logs.

**Comment by ArtificialQualia** [comment]
Thanks for the heads up!  CCP did indeed change their log file names with their new patch.  I have released a fix for PELD.  Please download [v2.7.1](https://github.com/ArtificialQualia/PyEveLiveDPS/releases/tag/v2.7.1) and let me know if you have any other issues.
