### ISSUE TITLE
Don't run on install or Add/restore "Don't run on install" option for the installer's silent flags

### ISSUE THREAD

**Issue by superusercode** [ArtificialQualia/PyEveLiveDPS#85]
PyEveLiveDPS currently launches right after being installed, which is unexpected when setting up a pc after a clean  install and also prevent a proper silent install using the inno setup silent install flags.

**Comment by ArtificialQualia** [comment]
Thanks for your feedback.  It makes sense to add this as I hadn't really considered those who would like to do a silent install.

I can update the postinstall options to change the default behavior and have PELD not open after install by default, which will still allow those who want to use that option to enable it when progressing through the GUI installer.

This isn't really a big enough change to justify a full release, but I'll see about attaching to this issue so users like you have an installer they can use until a new release is cut.

**Comment by ArtificialQualia** [comment]
Alright, I've cut a custom release including this fix.  I've uploaded it to the most recent release here:  
https://github.com/ArtificialQualia/PyEveLiveDPS/releases/tag/v2.7.2

You can download it directly too if you'd rather:  
https://github.com/ArtificialQualia/PyEveLiveDPS/releases/download/v2.7.2/PELD-installer-v2.7.2b.exe
