### ISSUE TITLE
Not Character detected

### ISSUE THREAD

**Issue by Kalmahar** [ArtificialQualia/PyEveLiveDPS#87]
Hello, I have a problem with the PELD program to find my EvE Online characters.

I've tried everything but it doesn't change anything, I need help please.
I'm on Steam, maybe the problem is there.

Thanks you so much and fly safe o/

I very want this application for my EvE stream <3

**Comment by ArtificialQualia** [comment]
Hi, I'm going to need a bit more information to be able to help you.  Could you please follow these instructions so I can take a look at the logs:

1. Open Windows File Explorer
2. Put `%APPDATA%\PELD` into your File Explorer navigation bar
3. Drag the `PELD.log` file from that folder into a reply to this issue

It would also be helpful if you could do the same for the latest EVE Gamelog file, as sometimes CCP changes the format of these logs without notice and that can trip up PELD:

1. Open Windows File Explorer
2. Put `%USERPROFILE%\Documents\EVE\logs\Gamelogs` into your File Explorer navigation bar
3. Drag the newest file that is larger than 1 KB, or the newest couple files from that folder into a reply to this issue

Then I can take a look at both of those and get back to you.

**Comment by ArtificialQualia** [comment]
It's been a couple weeks now and I haven't heard back from you, so I'm going to close out this issue for now.  Feel free to open another issue if you are still experiencing this problem and please attach the requested logs if so.  Thanks!
