### ISSUE TITLE
Fresh/clean install, window immediately closes again

### ISSUE THREAD

**Issue by muelli01** [ArtificialQualia/PyEveLiveDPS#88]
I tried the latest Version as install and standalone, both seem to try to open a new window but it immediately closes again.
I checked the Appdata directory and cleaned all files there, but it does not solve the problem.

Here is the log content:

```
2024-02-04 19:15:30,740:root:INFO - logger initialized
2024-02-04 19:15:30,740:root:INFO - changing log level to value in settings file...
2024-02-04 19:15:30,741:root:INFO - log level set to 20
2024-02-04 19:15:30,953:root:ERROR - (-2147352567, 'DISP_E_EXCEPTION', (0, None, None, None, 0, -2147467263), None)
Traceback (most recent call last):
  File "peld.py", line 62, in <module>
  File "peld.py", line 25, in __init__
  File "mainWindow.py", line 66, in __init__
  File "mainWindow.py", line 149, in addMenus
  File "logreader.py", line 170, in __init__
  File "site-packages\win32com\client\dynamic.py", line 192, in __call__
pywintypes.com_error: (-2147352567, 'DISP_E_EXCEPTION', (0, None, None, None, 0, -2147467263), None)
```

**Comment by ArtificialQualia** [comment]
Thanks for providing the logs, that really helps here.

This is certainly an unusual error, what version of windows are you on?

**Comment by muelli01** [comment]
Hmm I was afraid you would say that :) This is a WINE system set up as Windows 10. Eve is working like charm....
And before you ask: I tried the Python version as well, no luck with Python 3.7, 3.10 or 3.11

**Comment by ArtificialQualia** [comment]
Ah, yea well that certainly explains that! It's probably easier to avoid the WINE rabbit hole, and it's wholly unnecessary in this case anyways.

If you want to run it directly in Python, 3.6 is the last version supported.  

Given that's pretty old at this point, if you want I should be able to build a self-contained linux binary like the standalone windows one, might make it easier for you (and others) so you don't have to dig around for an ancient python version or deal with pip. Would that be good for you?

**Comment by muelli01** [comment]
Absolutely, if you can build a linux standalone binary that would be perfect :)
Thanks!

**Comment by ArtificialQualia** [comment]
Alright, I've made a linux binary `peld-linux` and uploaded it to the latest release:  
https://github.com/ArtificialQualia/PyEveLiveDPS/releases/tag/v2.7.2

Can you give that one a try?

**Comment by muelli01** [comment]
I tried it today and it works. Thanks a lot!

**Comment by muelli01** [comment]
I wanted to add, that I see a significant CPU usage even when not in battle. Around the same CPU usage as EVE itself.....
